# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "ar-api"

[default.build.parameters]
cached = false
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ar-api"
region = "ca-central-1"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[lza-dev]
[lza-dev.global.parameters]
stack_name = "ar-api-lza-dev"

[lza-dev.build.parameters]
cached = false
parallel = true

[lza-dev.validate.parameters]
lint = true

[lza-dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ar-api-lza-dev"
region = "ca-central-1"
image_repositories = []
parameter_overrides = [
  "TableNameAR=ParksAr-lza-dev",
  "TableNameCacheAR=NameCacheAr-lza-dev",
  "TableNameConfigAR=ConfigAr-lza-dev",
  "S3BucketData=parks-ar-export-data-lza-dev",
  "Stage=lza-dev"
]

[lza-dev.package.parameters]
resolve_s3 = true

[lza-dev.sync.parameters]
watch = true

[lza-dev.local_start_api.parameters]
warm_containers = "EAGER"

[lza-dev.local_start_lambda.parameters]
warm_containers = "EAGER"
