# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "ar-api"

[default.build.parameters]
cached = false
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ar-api"
region = "ca-central-1"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[lza-dev]
[lza-dev.global.parameters]
stack_name = "ar-api-lza-dev"

[lza-dev.build.parameters]
cached = false
parallel = true

[lza-dev.validate.parameters]
lint = true

[lza-dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ar-api-lza-dev"
region = "ca-central-1"
image_repositories = []
parameter_overrides = [
  "TableNameAR=ParksAr-lza-dev",
  "TableNameCacheAR=NameCacheAr-lza-dev",
  "TableNameConfigAR=ConfigAr-lza-dev",
  "S3BucketData=parks-ar-export-data-lza-dev",
  "Stage=lza-dev",
  "ExportFunctionName=ar-api-lza-dev-ExportInvokableFunction",
  "VarianceExportFunctionName=ar-api-lza-dev-VarianceExportInvokableFunction",
  "MissingExportFunctionName=ar-api-lza-dev-MissingExportInvokableFunction",
  "NameUpdateRuleName=NameUpdate-lza-dev"
]

[lza-dev.package.parameters]
resolve_s3 = true

[lza-dev.sync.parameters]
watch = true

[lza-dev.local_start_api.parameters]
warm_containers = "EAGER"

[lza-dev.local_start_lambda.parameters]
warm_containers = "EAGER"

[lza-test]
[lza-test.global.parameters]
stack_name = "ar-api-lza-test"

[lza-test.build.parameters]
cached = false
parallel = true

[lza-test.validate.parameters]
lint = true

[lza-test.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "ar-api-lza-test"
region = "ca-central-1"
image_repositories = []
parameter_overrides = [
  "TableNameAR=ParksAr-lza-test",
  "TableNameCacheAR=NameCacheAr-lza-test",
  "TableNameConfigAR=ConfigAr-lza-test",
  "S3BucketData=parks-ar-export-data-lza-test",
  "Stage=lza-test",
  "ExportFunctionName=ar-api-lza-test-ExportInvokableFunction",
  "VarianceExportFunctionName=ar-api-lza-test-VarianceExportInvokableFunction",
  "MissingExportFunctionName=ar-api-lza-test-MissingExportInvokableFunction",
  "NameUpdateRuleName=NameUpdate-lza-test"
]

[lza-test.package.parameters]
resolve_s3 = true

[lza-test.sync.parameters]
watch = true

[lza-test.local_start_api.parameters]
warm_containers = "EAGER"

[lza-test.local_start_lambda.parameters]
warm_containers = "EAGER"

[lza-prod]
[lza-prod.global.parameters]
stack_name = "ar-api-lza-prod"

[lza-prod.build.parameters]
cached = false
parallel = true

[lza-prod.validate.parameters]
lint = true

[lza-prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "ar-api-lza-prod"
region = "ca-central-1"
image_repositories = []
parameter_overrides = [
  "TableNameAR=ParksAr-lza-prod",
  "TableNameCacheAR=NameCacheAr-lza-prod",
  "TableNameConfigAR=ConfigAr-lza-prod",
  "S3BucketData=parks-ar-export-data-lza-prod",
  "Stage=api",
  "ExportFunctionName=ar-api-lza-prod-ExportInvokableFunction",
  "VarianceExportFunctionName=ar-api-lza-prod-VarianceExportInvokableFunction",
  "MissingExportFunctionName=ar-api-lza-prod-MissingExportInvokableFunction",
  "NameUpdateRuleName=NameUpdate-lza-prod"
]

[lza-prod.package.parameters]
resolve_s3 = true

[lza-prod.sync.parameters]
watch = true

[lza-prod.local_start_api.parameters]
warm_containers = "EAGER"

[lza-prod.local_start_lambda.parameters]
warm_containers = "EAGER"
